"use client";
import { useEffect, useState } from "react";

type Pattern = { id: string; label: string; detail: string; confidence: number };
type Model = { planning_style: string; workload: { open_tasks: number; overdue_tasks: number; due_today: number; active_projects: number; active_goals: number }; time_preferences: { preferred_start: string | null; preferred_end: string | null }; energy_preferences: { default_level: string | null; high_energy_tasks: number; low_energy_tasks: number }; behavioral_patterns: { completion_count: number; deferral_count: number; habit_signal_count: number; recommendation_feedback_count: number; recent_activity: string[]; most_active_hour: number | null; most_active_weekday: string | null; completion_rate: number | null; average_task_duration_minutes: number | null }; inferred_patterns: Pattern[]; priorities: { high_priority_tasks: string[]; active_goals: string[] }; memory_summary: { count: number; high_confidence: string[]; correction_count: number }; confidence: number };

export default function PersonalModelPage() {
  const [model, setModel] = useState<Model | null>(null);
  const [error, setError] = useState("");
  const [correction, setCorrection] = useState("");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");

  async function load() {
    try { const response = await fetch("/api/personal-model", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setModel(body.model); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load model."); }
  }
  useEffect(() => { void load(); }, []);

  async function saveCorrection() {
    if (!correction.trim()) return;
    setSaving(true); setMessage("");
    try { const response = await fetch("/api/personal-model/corrections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pattern: "personal model", correction }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setCorrection(""); setMessage("Rotean will use that correction going forward."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save correction."); } finally { setSaving(false); }
  }

  if (error) return <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><h1 className="text-xl font-semibold">Personal model</h1><p className="mt-2 text-sm text-[var(--danger)]">{error}</p></div>;
  if (!model) return <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 text-sm text-[var(--muted)]">Building your model…</div>;
  const cards = [[model.workload.open_tasks, "open tasks"], [model.workload.due_today, "due today"], [model.workload.overdue_tasks, "overdue"], [model.memory_summary.count, "memories"]];
  return <div className="space-y-7">
    <header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--green)]">Rotean Intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Your personal model.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Rotean learns from explicit preferences and observed behavior. Inferences stay probabilistic and can always be corrected.</p></header>
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{cards.map(([v, l]) => <div key={String(l)} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-2xl font-semibold">{v}</p><p className="mt-1 text-xs text-[var(--muted)]">{l}</p></div>)}</section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl bg-[var(--green)] p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-white/60">Planning</p><p className="mt-3 text-2xl font-semibold capitalize">{model.planning_style}</p><p className="mt-2 text-sm text-white/65">Preferred working window: {model.time_preferences.preferred_start}–{model.time_preferences.preferred_end}.</p></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--muted)]">Model confidence</p><p className="mt-3 text-2xl font-semibold">{Math.round(model.confidence * 100)}%</p><p className="mt-2 text-sm text-[var(--muted)]">Confidence grows with real behavioral evidence and explicit memories.</p></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Inferred patterns</h2><div className="mt-4 space-y-3">{model.inferred_patterns.length ? model.inferred_patterns.map((pattern) => <div key={pattern.id} className="rounded-2xl bg-[var(--background)] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{pattern.label}</p><span className="text-xs text-[var(--muted)]">{Math.round(pattern.confidence * 100)}%</span></div><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{pattern.detail}</p></div>) : <p className="text-sm text-[var(--muted)]">Not enough behavioral evidence yet. Keep using Rotean and it will learn gradually.</p>}</div></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Behavior</h2><p className="mt-2 text-sm text-[var(--muted)]">{model.behavioral_patterns.completion_count} completions · {model.behavioral_patterns.deferral_count} deferrals · {model.behavioral_patterns.habit_signal_count} habit signals.</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[var(--background)] p-3"><p className="text-lg font-semibold">{model.behavioral_patterns.completion_rate === null ? "—" : `${Math.round(model.behavioral_patterns.completion_rate * 100)}%`}</p><p className="text-xs text-[var(--muted)]">follow-through</p></div><div className="rounded-xl bg-[var(--background)] p-3"><p className="text-lg font-semibold">{model.behavioral_patterns.average_task_duration_minutes === null ? "—" : `${model.behavioral_patterns.average_task_duration_minutes}m`}</p><p className="text-xs text-[var(--muted)]">avg actual time</p></div></div><p className="mt-4 text-sm">{model.behavioral_patterns.most_active_hour === null ? "Not enough activity to infer an active hour." : `Most active around ${String(model.behavioral_patterns.most_active_hour).padStart(2, "0")}:00.`}{model.behavioral_patterns.most_active_weekday ? ` Strongest day: ${model.behavioral_patterns.most_active_weekday}.` : ""}</p></div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Current priorities</h2><div className="mt-4 space-y-3">{model.priorities.high_priority_tasks.length ? model.priorities.high_priority_tasks.map((x) => <p key={x} className="rounded-xl bg-[var(--background)] px-4 py-3 text-sm">{x}</p>) : <p className="text-sm text-[var(--muted)]">No high-priority tasks yet.</p>}</div></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Explicit memory</h2><p className="mt-2 text-sm text-[var(--muted)]">{model.memory_summary.count} stored memories · {model.memory_summary.correction_count} corrections.</p><div className="mt-4 grid gap-3">{model.memory_summary.high_confidence.length ? model.memory_summary.high_confidence.map((x) => <p key={x} className="rounded-xl bg-[var(--background)] px-4 py-3 text-sm">{x}</p>) : <p className="text-sm text-[var(--muted)]">No high-confidence memories yet.</p>}</div></div></section>
    <section className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--green)]">Teach Rotean</p><h2 className="mt-2 text-xl font-semibold">Correct an assumption</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">If Rotean gets a pattern wrong, tell it directly. Corrections become explicit, high-confidence memories instead of silently overriding the evidence.</p><textarea value={correction} onChange={(e) => setCorrection(e.target.value)} placeholder="e.g. I actually prefer deep work late at night." className="mt-4 min-h-28 w-full rounded-2xl border border-[var(--line)] bg-[var(--background)] p-4 text-sm outline-none focus:border-[var(--green)]" /><div className="mt-3 flex items-center gap-3"><button onClick={saveCorrection} disabled={saving || !correction.trim()} className="rounded-xl bg-[var(--green)] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save correction"}</button>{message && <span className="text-sm text-[var(--muted)]">{message}</span>}</div></section>
  </div>;
}
