"use client";

import { useEffect, useState } from "react";

type Model = { planning_style: string; workload: { open_tasks: number; overdue_tasks: number; due_today: number; active_projects: number; active_goals: number }; time_preferences: { preferred_start: string | null; preferred_end: string | null }; energy_preferences: { default_level: string | null; high_energy_tasks: number; low_energy_tasks: number }; behavioral_patterns: { completion_count: number; deferral_count: number; habit_signal_count: number; recent_activity: string[] }; priorities: { high_priority_tasks: string[]; active_goals: string[] }; memory_summary: { count: number; high_confidence: string[] }; confidence: number };

export default function PersonalModelPage() {
  const [model, setModel] = useState<Model | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/personal-model").then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error); setModel(body.model); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load model.")); }, []);
  if (error) return <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><h1 className="text-xl font-semibold">Personal model</h1><p className="mt-2 text-sm text-[var(--danger)]">{error}</p></div>;
  if (!model) return <div className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 text-sm text-[var(--muted)]">Building your model…</div>;
  const cards = [[model.workload.open_tasks, "open tasks"], [model.workload.due_today, "due today"], [model.workload.overdue_tasks, "overdue"], [model.memory_summary.count, "memories"]];
  return <div className="space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--green)]">Rotean Intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em]">Your personal model.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">A structured picture of how your life is currently working. It gets better as Rotean observes real decisions and activity.</p></header><section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{cards.map(([value,label]) => <div key={label} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-4"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-[var(--muted)]">{label}</p></div>)}</section><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl bg-[var(--green)] p-6 text-white"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-white/60">Planning</p><p className="mt-3 text-2xl font-semibold capitalize">{model.planning_style}</p><p className="mt-2 text-sm text-white/65">Preferred working window: {model.time_preferences.preferred_start}–{model.time_preferences.preferred_end}.</p></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--muted)]">Energy</p><p className="mt-3 text-xl font-semibold capitalize">Default: {model.energy_preferences.default_level}</p><p className="mt-2 text-sm text-[var(--muted)]">{model.energy_preferences.high_energy_tasks} high-energy tasks · {model.energy_preferences.low_energy_tasks} low-energy tasks.</p></div></section><section className="grid gap-4 lg:grid-cols-2"><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><h2 className="font-semibold">Current priorities</h2><div className="mt-4 space-y-3">{model.priorities.high_priority_tasks.length ? model.priorities.high_priority_tasks.map((x) => <p key={x} className="rounded-xl bg-[var(--background)] px-4 py-3 text-sm">{x}</p>) : <p className="text-sm text-[var(--muted)]">No high-priority tasks yet.</p>}</div></div><div className="rounded-3xl border border-[var(--line)] bg-[var(--surface)] p-6"><h2 className="font-semibold">What Rotean has learned</h2><p className="mt-2 text-sm text-[var(--muted)]">Model confidence: {Math.round(model.confidence * 100)}%</p><div className="mt-4 space-y-3">{model.memory_summary.high_confidence.length ? model.memory_summary.high_confidence.map((x) => <p key={x} className="rounded-xl bg-[var(--background)] px-4 py-3 text-sm">{x}</p>) : <p className="text-sm text-[var(--muted)]">Add memories and use Rotean normally; the model will become more useful over time.</p>}</div></div></section></div>;
}
